export {
  type SqliteStorageErrorCode,
  type SqliteStorageErrorOptions,
  type MigrationFailedErrorDetails,
  type SchemaVersionUnsupportedDetails,
  type TransactionErrorCode,
  type ExecutionLockHeldDetails,
  type ListingIdentityCollisionDetails,
  SqliteStorageError,
  DatabaseOpenFailedError,
  DatabaseClosedError,
  PragmaConfigurationError,
  MigrationFailedError,
  MigrationManifestInvalidError,
  SchemaVersionUnsupportedError,
  TransactionFailedError,
  TransactionAsyncCallbackUnsupportedError,
  TransactionScopeClosedError,
  InvalidDatabasePathError,
  StorageCorruptionError,
  ExecutionLockHeldError,
  ExecutionLockReleaseError,
  ListingIdentityCollisionError,
  SensitiveDataDetectedError,
  isSqliteStorageError,
} from './storage-errors.js';
