export const CONFIGURATION_ERROR_CODES = [
  'CONFIG_PARSE_ERROR',
  'CONFIG_SCHEMA_VERSION_REQUIRED',
  'CONFIG_SCHEMA_VERSION_UNSUPPORTED',
  'CONFIG_SCHEMA_VALIDATION_ERROR',
  'CONFIG_SECRET_FORBIDDEN',
  'CONFIG_INVARIANT_VIOLATION',
  'CONFIG_CAPABILITY_MISMATCH',
  'CONFIG_SOURCE_NOT_REGISTERED',
  'CONFIG_SOURCE_DISABLED',
  'CONFIG_MIGRATION_ERROR',
  'REGISTRY_DUPLICATE_SOURCE',
  'REGISTRY_INCOMPATIBLE_SDK',
  'REGISTRY_FACTORY_MISMATCH',
  'REGISTRY_INVALID_ENTRY',
] as const;

export type ConfigurationErrorCode = (typeof CONFIGURATION_ERROR_CODES)[number];

export const isConfigurationErrorCode = (code: string): code is ConfigurationErrorCode =>
  (CONFIGURATION_ERROR_CODES as readonly string[]).includes(code);
